version: '3.8'

services:
  activemq:
    image: rmohr/activemq:latest
    container_name: activemq-Bank
    restart: always
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ACTIVEMQ_CONFIG_MINMEMORY: 512
      ACTIVEMQ_CONFIG_MAXMEMORY: 2048
    networks:
      - backend

networks:
  backend:
    driver: bridge
