server:
  port: 8082

spring:
  application:
    name: merchant-bank-service

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

  datasource:
    url: jdbc:h2:mem:merchantdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
