server:
  port: 8080

spring:
  application:
    name: gateway-service
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.jms: DEBUG
    org.apache.activemq: DEBUG