server:
  port: 8081

spring:
  application:
    name: client-bank-service

  h2:
    console:
      enabled: true
      path: /h2-console

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

  datasource:
    url: jdbc:h2:mem:clientdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password: ""
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: none   # on initialise via schema.sql
    show-sql: true
